#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 04 10:33:21 CET 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_sobelProc_behav -key {Behavioral:sim_1:Functional:tb_sobelProc} -tclbatch tb_sobelProc.tcl -view /homes/g24obuzo/Documents/UEF_Integrated_Electronics/TP2_Sobel/sobel/tb_sobelProc_behav.wcfg -log simulate.log"
xsim tb_sobelProc_behav -key {Behavioral:sim_1:Functional:tb_sobelProc} -tclbatch tb_sobelProc.tcl -view /homes/g24obuzo/Documents/UEF_Integrated_Electronics/TP2_Sobel/sobel/tb_sobelProc_behav.wcfg -log simulate.log

